spring:
  application:
    name: service-auth
  redis:
    host: 10.243.1.203
    password: 123456  ## Redis服务器连接密码（默认为空）
    database: 1


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

#logging.level.org.springframework.security: DEBUG

